apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{ if .Values.webhookingester.useReloader }}
      configmap.reloader.stakater.com/reload: "publisher-configmap"
    {{ else }}
  name: moscars-webhookingester-publisher
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.webhookingester.publisher.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  selector:
    matchLabels:
      app: moscars-webhookingester-publisher
  template:
    metadata:
      labels:
        app: moscars-webhookingester-publisher
    spec:
      volumes:
        - name: publisher-configmap-volume
          configMap:
            name: publisher-configmap
      containers:
        - name: moscars-webhookingester-publisher
          image: {{ .Values.webhookingester.publisher.image }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: publisher-configmap-volume
              mountPath: /etc/config
          env:
            - name: WEBHOOKINGESTER_NATSURL
              value: {{ .Values.webhookingester.natsUrl }}
          resources:
            requests:
              memory: '50Mi'
              cpu: '200m'
            limits:
              memory: '200Mi'
              cpu: '400m'
