apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscars-webhookingester-publisher
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.publisher.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  selector:
    matchLabels:
      app: moscars-webhookingester-publisher
  template:
    metadata:
      labels:
        app: moscars-webhookingester-publisher
    spec:
      containers:
        - name: moscars-webhookingester-publisher
          image: {{ .Values.publisher.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: WEBHOOKINGESTER_NATSURL
              value: {{ .Values.nats.url }}
          resources:
            requests:
              memory: '50Mi'
              cpu: '200m'
            limits:
              memory: '200Mi'
              cpu: '400m'
