apiVersion: v1
kind: Service
metadata:
  name: moscars-webhookingester-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: moscars-webhookingester-api
spec:
  type: ClusterIP
  selector:
    app: moscars-webhookingester-api
  ports:
  - port: 8080
    name: service-http
    protocol: TCP
    targetPort: http