webhookingester:
  natsUrl: ""
  deployOwnNats: true
  deployOwnReloader: true
  useReloader: true
  api:
    image: moscars-webhookingester-api:latest
    replicas: 1
    apikey: SuperSecureKey
  
  publisher:
    image: moscars-webhookingester-publisher:latest
    replicas: 3

nats:
  cluster:
    enabled: true
    replicas: 2
  nats:
    jetstream:
      enabled: true

      memStorage:
        enabled: true
        size: 1Gi

      fileStorage:
        enabled: true
        size: 1Gi
        storageDirectory: /data/

reloader:
  watchGlobally: false
  ignoreSecrets: true
  namespaceSelector: default