api:
  image: moscars-webhookingester-api:latest
  replicas: 1
  apikey: "SuperSecureKey"
publisher:
  image: moscars-webhookingester-publisher:latest
  replicas: 3
nats:
  url: moscars-webhookingester-nats.default.svc.cluster.local:4222
  cluster:
    enabled: true
    replicas: 2
  nats:
    jetstream:
      enabled: true

      memStorage:
        enabled: true
        size: 1Gi

      fileStorage:
        enabled: true
        size: 1Gi
        storageDirectory: /data/
reloader:
  watchGlobally: false